import Head from 'next/head'
import About from '../Components/About'
import Banner from '../Components/Banner'
import Contact from '../Components/Contact'
import Footer from '../Components/Footer'
import Header from '../Components/Header'
import Skills from '../Components/Skills'
import Work from '../Components/Work'

import { useEffect, useState } from 'react'
// import Dropdown from '../Components/Dropdown'





export default function Home() {
  const[open,Setopen]=useState(false);
  const toogle=()=> {
    Setopen(!open)
  }



  

  return (
    <div >
      <Head>
        <title>Mayank Saxena | Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

    

      <Header   />
   
      <Banner  toogle={toogle} open={!open}/>
  
      <main  className="max-w-6xl  mx-auto  ">
      <About />
      <Skills />
      <Work />
     
   

     
      </main>
      <Contact />
      <Footer />


    </div>

  
  )
}
